### ISSUE TITLE
TypeError: Object [object Object] has no method 'findIndex'

### ISSUE THREAD

**Issue by Ishneetkaur** [tannerlinsley/react-table#106]
TypeError: Object [object Object] has no method 'findIndex'
    at null.getDataModel (/opt/www/webapp/node_modules/react-table/src/methods.js:48:39)
    at null.componentWillMount (/opt/www/webapp/node_modules/react-table/src/lifecycle.js:29:32)
    at /opt/www/webapp/node_modules/react-dom/lib/ReactCompositeComponent.js:348:23
    at measureLifeCyclePerf (/opt/www/webapp/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
    at null.ReactCompositeComponent.performInitialMount (/opt/www/webapp/node_modules/react-dom/lib/ReactCompositeComponent.js:347:9)
    at null.ReactCompositeComponent.mountComponent (/opt/www/webapp/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.ReactReconciler.mountComponent (/opt/www/webapp/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (/opt/www/webapp/node_modules/react-dom/lib/ReactMultiChild.js:238:44)
    at ReactDOMComponent.Mixin._createContentMarkup (/opt/www/webapp/node_modules/react-dom/lib/ReactDOMComponent.js:653:32)
    at ReactDOMComponent.Mixin.mountComponent (/opt/www/webapp/node_modules/react-dom/lib/ReactDOMComponent.js:520:29)

**Comment by tannerlinsley** [comment]
What browser, browser version and library version are you using?

**Comment by Ishneetkaur** [comment]
I just used babel-polyfill and it worked. I tried in all browsers and they were latest versions.

**Comment by tannerlinsley** [comment]
Interesting. Glad it worked out!

**Comment by marudhupandiyang** [comment]
I encountered the same issue somedays back on IE 10 and solved it using `babel-polyfill`.
Similar errors(`no method`) i encountered are `Array.findIndex`, `Array.find`, `Object.assign` and `Set` objects. 
There is no mention(or i could find of) of IE support for this library i believe ?

**Comment by tannerlinsley** [comment]
Deliberate mention of support... No not yet. I would accept a PR to the
readme though that mentions it :)
