### ISSUE TITLE
TypeError: column.getSortByToggleProps is not a function

### ISSUE THREAD

**Issue by slowtarget** [tannerlinsley/react-table#1744]
https://codesandbox.io/s/github/tannerlinsley/react-table/tree/master/examples/pagination-controlled

is currently failing to render due to this error.

v7: Yes

```
$ grep react-table package-lock.json
    "react-table": {
      "resolved": "https://registry.npmjs.org/react-table/-/react-table-7.0.0-rc.6.tgz",
```

```$ npm test

> @ test C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled
> rescripts test

FAIL src/App.test.js
  × renders without crashing (46ms)

  ● renders without crashing

    TypeError: column.getSortByToggleProps is not a function

      106 |             <tr {...headerGroup.getHeaderGroupProps()}>
      107 |               {headerGroup.headers.map(column => (
    > 108 |                 <th {...column.getHeaderProps(column.getSortByToggleProps())}>
          |                                                      ^
      109 |                   {column.render('Header')}
      110 |                   <span>
      111 |                     {column.isSorted

      at map (src/App.js:108:54)
          at Array.map (<anonymous>)
      at map (src/App.js:107:36)
          at Array.map (<anonymous>)
      at Table (src/App.js:105:25)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:16260:18)
      at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:18794:13)
      at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:20162:16)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:336:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:385:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:440:31)
      at beginWork$$1 (node_modules/react-dom/cjs/react-dom.development.js:25780:7)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:24698:12)
      at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:24671:22)
      at performSyncWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:24270:11)
      at scheduleUpdateOnFiber (node_modules/react-dom/cjs/react-dom.development.js:23698:7)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:27103:3)
      at node_modules/react-dom/cjs/react-dom.development.js:27528:7
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:24433:12)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:27527:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:27608:10)
      at Object.<anonymous>.it (src/App.test.js:7:12)

  console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Uncaught [TypeError: column.getSortByToggleProps is not a function]
        at reportException (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\jsdom\lib\jsdom\living\helpers\runtime-script-errors.js:66:24)
        at invokeEventListeners (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:209:9)
        at HTMLUnknownElementImpl._dispatch (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\jsdom\lib\jsdom\living\nodes\HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\react-dom\cjs\react-dom.development.js:385:16)
        at invokeGuardedCallback (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\react-dom\cjs\react-dom.development.js:440:31)
        at beginWork$$1 (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\react-dom\cjs\react-dom.development.js:25780:7)
        at performUnitOfWork (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\react-dom\cjs\react-dom.development.js:24698:12) TypeError: column.getSortByToggleProps is not a function
        at map (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\src\App.js:108:54)
        at Array.map (<anonymous>)
        at map (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\src\App.js:107:36)
        at Array.map (<anonymous>)
        at Table (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\src\App.js:105:25)
        at renderWithHooks (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\react-dom\cjs\react-dom.development.js:16260:18)
        at mountIndeterminateComponent (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\react-dom\cjs\react-dom.development.js:18794:13)
        at beginWork$1 (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\react-dom\cjs\react-dom.development.js:20162:16)
        at HTMLUnknownElement.callCallback (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\react-dom\cjs\react-dom.development.js:336:14)
        at invokeEventListeners (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:193:27)
        at HTMLUnknownElementImpl._dispatch (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:119:9)
        at HTMLUnknownElementImpl.dispatchEvent (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:82:17)
        at HTMLUnknownElementImpl.dispatchEvent (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\jsdom\lib\jsdom\living\nodes\HTMLElement-impl.js:30:27)
        at HTMLUnknownElement.dispatchEvent (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:157:21)
        at Object.invokeGuardedCallbackDev (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\react-dom\cjs\react-dom.development.js:385:16)
        at invokeGuardedCallback (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\react-dom\cjs\react-dom.development.js:440:31)
        at beginWork$$1 (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\react-dom\cjs\react-dom.development.js:25780:7)
        at performUnitOfWork (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\react-dom\cjs\react-dom.development.js:24698:12)
        at workLoopSync (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\react-dom\cjs\react-dom.development.js:24671:22)
        at performSyncWorkOnRoot (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\react-dom\cjs\react-dom.development.js:24270:11)
        at scheduleUpdateOnFiber (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\react-dom\cjs\react-dom.development.js:23698:7)
        at updateContainer (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\react-dom\cjs\react-dom.development.js:27103:3)
        at C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\react-dom\cjs\react-dom.development.js:27528:7
        at unbatchedUpdates (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\react-dom\cjs\react-dom.development.js:24433:12)
        at legacyRenderSubtreeIntoContainer (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\react-dom\cjs\react-dom.development.js:27527:5)
        at Object.render (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\react-dom\cjs\react-dom.development.js:27608:10)
        at Object.<anonymous>.it (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\src\App.test.js:7:12)
        at Object.asyncJestTest (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\jest-jasmine2\build\jasmineAsyncInstall.js:102:37)
        at resolve (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\jest-jasmine2\build\queueRunner.js:43:12)
        at new Promise (<anonymous>)
        at mapper (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\jest-jasmine2\build\queueRunner.js:26:19)
        at promise.then (C:\Users\jason.farmer\Downloads\tannerlinsley-react-table-pagination-controlled\node_modules\jest-jasmine2\build\queueRunner.js:73:41)
        at process._tickCallback (internal/process/next_tick.js:68:7)

  console.error node_modules/react-dom/cjs/react-dom.development.js:21843
    The above error occurred in the <Table> component:
        in Table (at App.js:278)
        in div (created by Context.Consumer)
        in StyledComponent (created by styled.div)
        in styled.div (at App.js:277)
        in App (at App.test.js:7)

    Consider adding an error boundary to your tree to customize error handling behavior.
    Visit https://fb.me/react-error-boundaries to learn more about error boundaries.

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        3.708s
Ran all test suites.
```

**Comment by tannerlinsley** [comment]
Just fixed this before I saw this issue :)
