### ISSUE TITLE
Unable to display last page when accessing rowInfo with getTrProps

### ISSUE THREAD

**Issue by witcradg** [tannerlinsley/react-table#233]
## Problem Description
I'm wondering if I missed something in the docs. This seems like it should be straightforward.
I'm displaying 150 rows in a simple table. If I don't try to use the getTrProps method I can view all pages without a problem.
When I use getTrProps all pages except the final page display fine using the Next and Previous features.
When I try to access the final page, getTrProps is called at some point with rowInfo undefined.
Could this be because the final page has fewer rows than the page size?

Note regarding the source code below: The rowInfo.row.status (where status is the user defined attribute) is not identical to the documentation where rowInfo.age is used (just the rowInfo and user attribute). Is the documentation out of date in this regard? In order to access my data I had to use rowInfo.row.status.

The console shows the following:

Dashboard.js:80 Uncaught TypeError: Cannot read property 'row' of undefined
    at getTrProps (http://localhost:3000/static/js/bundle.js:33466:49)
    at makePadRow (http://localhost:3000/static/js/bundle.js:34285:51)
    at Array.map (native)
    at makeTable (http://localhost:3000/static/js/bundle.js:34436:24)
    at ReactTable.render (http://localhost:3000/static/js/bundle.js:34462:66)
    at http://localhost:3000/static/js/bundle.js:26931:22
    at measureLifeCyclePerf (http://localhost:3000/static/js/bundle.js:26210:13)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://localhost:3000/static/js/bundle.js:26930:26)
    at ReactCompositeComponentWrapper._renderValidatedComponent (http://localhost:3000/static/js/bundle.js:26957:33)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://localhost:3000/static/js/bundle.js:26881:37)

To prevent the funtion from doing anything without a valid rowInfo I tried adding the conditional
`	if (rowInfo && rowInfo.row) `
This just seems to move the problem elsewhere producing this error

utils.js:203 Uncaught TypeError: Cannot read property 'className' of undefined
    at Object.splitProps (http://localhost:3000/static/js/bundle.js:34741:25)
    at makePadRow (http://localhost:3000/static/js/bundle.js:34287:40)
    at Array.map (native)
    at makeTable (http://localhost:3000/static/js/bundle.js:34438:24)
    at ReactTable.render (http://localhost:3000/static/js/bundle.js:34464:66)
    at http://localhost:3000/static/js/bundle.js:26931:22
    at measureLifeCyclePerf (http://localhost:3000/static/js/bundle.js:26210:13)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://localhost:3000/static/js/bundle.js:26930:26)
    at ReactCompositeComponentWrapper._renderValidatedComponent (http://localhost:3000/static/js/bundle.js:26957:33)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://localhost:3000/static/js/bundle.js:26881:37)

## Code Snippet(s)
`data structure:
Array[151]
Object
{
  "process": "myProcessName",
  "monitor": "myMonitorName",
  "status": "OK",
}

source code:

    render() {
        let data = this.state.pageData;
        if (data.length === 0) return (<div>Loading...</div>);

        const columns = [{
            header: 'Process',
            accessor: 'process',
        }, {
            header: 'Monitor',
            accessor: 'monitor',
        }, {
            header: 'Status',
            accessor: 'status',
            show: false
        }];
        return <ReactTable data={data} columns={columns}
                           defaultSorting={[{id: 'status'}]}
                           getTrProps={(state, rowInfo) => {
                               if (rowInfo && rowInfo.row) {
                                   return {
                                       style: {
                                           background: rowInfo.row.status === 'OK' ? 'green' : 'red'
                                       }
                                   }
                               }
                           }}/>
    }
`
## Steps to Reproduce
Run the program to load and display the data. The first page of the table will display.
use the next button to page through the data
access the final page. The page will not display

## System Information
Chrome Version 57.0.2987.133
node -v v6.10.0
Window 7 Professional
npm -v 4.5.0

**Comment by tannerlinsley** [comment]
You are correct, the docs should read `rowInfo.row.age`.  As for the
problem you are having, you need to remember that technically there can be
TR’s that have no data if padding row’s are being shown.  You should always
check to make sure the property you need is there for any `getThingProps`
prop. In this case, it is probably a padding row that is calling
`getTrProps`.  Since padding rows have no data, none will be sent.  Hope
that clears things up.

**Comment by witcradg** [comment]
I'm not sure how to handle the condition. 
To prevent the function from doing anything without a valid rowInfo I tried adding the conditional
	`if (rowInfo && rowInfo.row) `
This just seems to move the problem elsewhere producing a different exception

 `     return <ReactTable data={data} columns={columns}
                           defaultSorting={[{id: 'STATUS_TXT'}]}
                           getTrProps={(state, rowInfo) => {
                               if (rowInfo && rowInfo.row) {
                                   return {
                                       style: {
                                           background: rowInfo.row.STATUS_TXT === 'OK' ? 'green' : 'red'
                                       } } } }}/>
`
`utils.js:203 Uncaught TypeError: Cannot read property 'className' of undefined
    at Object.splitProps (http://localhost:3000/static/js/bundle.js:34741:25)
    at makePadRow (http://localhost:3000/static/js/bundle.js:34287:40)
    at Array.map (native)
    at makeTable (http://localhost:3000/static/js/bundle.js:34438:24)
    at ReactTable.render (http://localhost:3000/static/js/bundle.js:34464:66)
    at http://localhost:3000/static/js/bundle.js:26931:22
    at measureLifeCyclePerf (http://localhost:3000/static/js/bundle.js:26210:13)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://localhost:3000/static/js/bundle.js:26930:26)
    at ReactCompositeComponentWrapper._renderValidatedComponent (http://localhost:3000/static/js/bundle.js:26957:33)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://localhost:3000/static/js/bundle.js:26881:37)
`

**Comment by aaronschwartz** [comment]
`getTrProps` expects you to return an object and not `undefined`. 
If you override it you have to make sure that all paths return some kind of object.
Try returning an empty object in your else statement.
```
if(rowInfo && rowInfo.row) {
...
}
else {
  return {}
}
```

**Comment by witcradg** [comment]
Impressive response time. You gave me an answer before I'd even finished cleaning up my question :+1:  (Still learning about markdown). Returning an object completely handled the issue, thanks. I'd tried explicitly returning null but not an empty object.

**Comment by aaronschwartz** [comment]
Glad it worked. I've run into it in the past. Maybe we should make the library a little more forgiving about null and undefined.
